### ISSUE TITLE
我用的这款插件，可能也适合作者用吧

### ISSUE THREAD

**Issue by doKill** [Summer-andy/chrome-extensions-searchReplace#3]
https://chrome.google.com/webstore/detail/search-and-replace/bldchfkhmnkoimaciljpilanilmbnofo

**Comment by Summer-andy** [comment]
我一开始也是用这个插件, 用这个插件替换文本后, 页面的事件就失效了。

**Comment by doKill** [comment]
> 我一开始也是用这个插件, 用这个插件替换文本后, 页面的事件就失效了。

我刚才在超链接和按钮上都试了一下没有问题，可能你用的那时候有些bug吧

**Comment by Summer-andy** [comment]
我不太清楚, 他是如何处理DOM的, 我看了一下插件的评论, 蛮多人也反馈有这个问题。
